raw_vcf: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/RawVCF/Chr1_renamed.vcf.gz"
aligned_focal: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/testAligned.txt"
no_estsfs_chunks: 3
estsfs_config: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/config-kimura_3o.txt"
estsfs_seed: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/seedfile.txt"
