rawVcf: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/RawVCF/Chr1_renamed.vcf.gz"
alignedFocal: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/testAligned.txt"
noEstSfsChunks: 3
estsfsConfig: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/config-kimura_3o.txt"
estsfsSeed: "/home/v1jobste/jobsteter/HighlanderLab/share/Snakemake/Data/seedfile.txt"


